services:
  mongo:
    image: mongo:7.0.20
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=7solutions
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:ro